DROP INDEX IF EXISTS SaveBlocks_GameID_ind;
DROP TABLE IF EXISTS SaveBlocks;

CREATE TABLE SaveBlocks (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  GameID INTEGER NOT NULL,
  BlockNumber INTEGER NOT NULL,
  Chip INTEGER NOT NULL,
  Address INTEGER NOT NULL,
  Size INTEGER NOT NULL,
  FOREIGN KEY (GameID) REFERENCES Games (ID)
);

CREATE INDEX SaveBlocks_GameID_ind ON SaveBlocks (GameID);
